const cars = [
  {
    _id: "001",
    title: "Lamborghini Aventador Lp700-4 ",
    brand: "Lamborghini",
    model: "Aventador",
    price: "2,49,00,000",
    registrationYear: "2019",
    registrationState: "Delhi",
    registrationNumber: "112233",
    kmDriven: "3500",
    fuelType: "Petrol",
    engineType: "1993cc, Turbocharged, In-Line 4 Cyl, DOHC",
    torque: "440 NM @ 1800 RPM",
    power: "197PS / 194BHP @ 3600 RPM",
    transmission: "9G-TRONIC Automatic Transmission",
    driveTrain: "RWD",
    thumbnail: "/images/collection/car-7.webp",
    gallery: [
      "/images/collection/car-7.webp",
      "/images/collection/car-7.webp",
      "/images/collection/car-7.webp",
    ],
    isBooked: false,
    isSoldOut: false,
    isCertified: true,
  },
  {
    _id: "002",
    title: "Mercedes benz EQS 580 4matic",
    brand: "Mercedes Benz",
    model: "Bentayga",
    price: "1,19,00,000",
    registrationYear: "2020",
    registrationState: "Delhi",
    registrationNumber: "112233",
    kmDriven: "3500",
    fuelType: "Petrol",
    engineType: "1993cc, Turbocharged, In-Line 4 Cyl, DOHC",
    torque: "440 NM @ 1800 RPM",
    power: "197PS / 194BHP @ 3600 RPM",
    transmission: "9G-TRONIC Automatic Transmission",
    driveTrain: "RWD",
    thumbnail: "/images/collection/car-8.webp",
    gallery: [
      "/images/collection/car-8.webp",
      "/images/collection/car-8.webp",
      "/images/collection/car-8.webp",
    ],
    isBooked: true,
    isSoldOut: false,
    isCertified: true,
  },
  {
    _id: "003",
    title: "Rolls Royce Ghost Series I",
    brand: "Rolls Royce ",
    model: "Ghost Series I",
    price: "1,89,00,000",
    registrationYear: "2012",
    registrationState: "Delhi",
    registrationNumber: "112233",
    kmDriven: "3500",
    fuelType: "Petrol",
    engineType: "1993cc, Turbocharged, In-Line 4 Cyl, DOHC",
    torque: "440 NM @ 1800 RPM",
    power: "197PS / 194BHP @ 3600 RPM",
    transmission: "9G-TRONIC Automatic Transmission",
    driveTrain: "RWD",
    thumbnail: "/images/collection/car-9.webp",
    gallery: [
      "/images/collection/car-9.webp",
      "/images/collection/car-9.webp",
      "/images/collection/car-9.webp",
    ],
    isBooked: false,
    isSoldOut: false,
    isCertified: false,
  },
  {
    _id: "004",
    title: "Rolls-Royce Ghost Series II",
    brand: "Rolls-Royce",
    model: "Ghost Series II",
    price: "4,99,00,000",
    registrationYear: "2022",
    registrationState: "Delhi",
    registrationNumber: "112233",
    kmDriven: "3500",
    fuelType: "Petrol",
    engineType: "1993cc, Turbocharged, In-Line 4 Cyl, DOHC",
    torque: "440 NM @ 1800 RPM",
    power: "197PS / 194BHP @ 3600 RPM",
    transmission: "9G-TRONIC Automatic Transmission",
    driveTrain: "RWD",
    thumbnail: "/images/collection/car-1.webp",
    gallery: [
      "/images/collection/car-1.webp",
      "/images/collection/car-1.webp",
      "/images/collection/car-1.webp",
    ],
    isBooked: false,
    isSoldOut: false,
    isCertified: false,
  },
  {
    _id: "005",
    title: "2018 Bentley Bentayga",
    brand: "Bentley",
    model: "Bentayga",
    price: "3,55,00,000",
    registrationYear: "2019",
    registrationState: "Delhi",
    registrationNumber: "112233",
    kmDriven: "3500",
    fuelType: "Petrol",
    engineType: "1993cc, Turbocharged, In-Line 4 Cyl, DOHC",
    torque: "440 NM @ 1800 RPM",
    power: "197PS / 194BHP @ 3600 RPM",
    transmission: "9G-TRONIC Automatic Transmission",
    driveTrain: "RWD",
    thumbnail: "/images/collection/car-2.webp",
    gallery: [
      "/images/collection/car-2.webp",
      "/images/collection/car-2.webp",
      "/images/collection/car-2.webp",
    ],
    isBooked: false,
    isSoldOut: false,
    isCertified: true,
  },
  {
    _id: "006",
    title: "2022 BMW Z4 M40I",
    brand: "BMW",
    model: "Z4 M40I",
    price: "3,55,00,000",
    registrationYear: "2022",
    registrationState: "Delhi",
    registrationNumber: "112233",
    kmDriven: "3500",
    fuelType: "Petrol",
    engineType: "1993cc, Turbocharged, In-Line 4 Cyl, DOHC",
    torque: "440 NM @ 1800 RPM",
    power: "197PS / 194BHP @ 3600 RPM",
    transmission: "9G-TRONIC Automatic Transmission",
    driveTrain: "RWD",
    thumbnail: "/images/collection/car-3.webp",
    gallery: [
      "/images/collection/car-3.webp",
      "/images/collection/car-3.webp",
      "/images/collection/car-3.webp",
    ],
    isBooked: false,
    isSoldOut: false,
    isCertified: false,
  },
];

export default cars;
