 const cars = [
  {
    _id: "001",
    title: "Rolls-Royce Ghost Series II",
    brand: "Rolls-Royce",
    model: "Ghost Series II",
    price: "4,99,00,000",
    registrationYear: "2022",
    registrationState: "Delhi",
    registrationNumber: "112233",
    kmDriven: "3500",
    fuelType: "Petrol",
    engineType: "1993cc, Turbocharged, In-Line 4 Cyl, DOHC",
    torque: "440 NM @ 1800 RPM",
    power: "197PS / 194BHP @ 3600 RPM",
    transmission: "9G-TRONIC Automatic Transmission",
    driveTrain: "RWD",
    thumbnail: "/images/collection/car-1.webp",
    gallery: [
      "/images/collection/car-1.webp",
      "/images/collection/car-1.webp",
      "/images/collection/car-1.webp",
    ],
    isBooked: false,
    isSoldOut: false,
    isCertified: false,
  },
  {
    _id: "002",
    title: "2018 Bentley Bentayga",
    brand: "Bentley",
    model: "Bentayga",
    price: "3,55,00,000",
    registrationYear: "2019",
    registrationState: "Delhi",
    registrationNumber: "112233",
    kmDriven: "3500",
    fuelType: "Petrol",
    engineType: "1993cc, Turbocharged, In-Line 4 Cyl, DOHC",
    torque: "440 NM @ 1800 RPM",
    power: "197PS / 194BHP @ 3600 RPM",
    transmission: "9G-TRONIC Automatic Transmission",
    driveTrain: "RWD",
    thumbnail: "/images/collection/car-2.webp",
    gallery: [
      "/images/collection/car-2.webp",
      "/images/collection/car-2.webp",
      "/images/collection/car-2.webp",
    ],
    isBooked: false,
    isSoldOut: false,
    isCertified: true,
  },
  {
    _id: "003",
    title: "2022 BMW Z4 M40I",
    brand: "BMW",
    model: "Z4 M40I",
    price: "3,55,00,000",
    registrationYear: "2022",
    registrationState: "Delhi",
    registrationNumber: "112233",
    kmDriven: "3500",
    fuelType: "Petrol",
    engineType: "1993cc, Turbocharged, In-Line 4 Cyl, DOHC",
    torque: "440 NM @ 1800 RPM",
    power: "197PS / 194BHP @ 3600 RPM",
    transmission: "9G-TRONIC Automatic Transmission",
    driveTrain: "RWD",
    thumbnail: "/images/collection/car-3.webp",
    gallery: [
      "/images/collection/car-3.webp",
      "/images/collection/car-3.webp",
      "/images/collection/car-3.webp",
    ],
    isBooked: false,
    isSoldOut: false,
    isCertified: false,
  },
  {
    _id: "004",
    title: "Lamborghini Urus",
    brand: "Lamborghini",
    model: "Urus",
    price: "3,65,00,000",
    registrationYear: "2020",
    registrationState: "Delhi",
    registrationNumber: "112233",
    kmDriven: "3500",
    fuelType: "Petrol",
    engineType: "1993cc, Turbocharged, In-Line 4 Cyl, DOHC",
    torque: "440 NM @ 1800 RPM",
    power: "197PS / 194BHP @ 3600 RPM",
    transmission: "9G-TRONIC Automatic Transmission",
    driveTrain: "RWD",
    thumbnail: "/images/collection/car-4.webp",
    gallery: [
      "/images/collection/car-4.webp",
      "/images/collection/car-4.webp",
      "/images/collection/car-4.webp",
    ],
    isBooked: false,
    isSoldOut: false,
    isCertified: true,
  },
  {
    _id: "005",
    title: "Mercedes-Benz AMG G 63",
    brand: "Mercedes-Benz",
    model: "AMG G 63",
    price: "3,69,00,000",
    registrationYear: "2023",
    registrationState: "Delhi",
    registrationNumber: "112233",
    kmDriven: "3500",
    fuelType: "Petrol",
    engineType: "1993cc, Turbocharged, In-Line 4 Cyl, DOHC",
    torque: "440 NM @ 1800 RPM",
    power: "197PS / 194BHP @ 3600 RPM",
    transmission: "9G-TRONIC Automatic Transmission",
    driveTrain: "RWD",
    thumbnail: "/images/collection/car-5.webp",
    gallery: [
      "/images/collection/car-5.webp",
      "/images/collection/car-5.webp",
      "/images/collection/car-5.webp",
    ],
    isBooked: false,
    isSoldOut: true,
    isCertified: false,
  },
  {
    _id: "006",
    title: "Range Rover Sport  HSE",
    brand: "Range Rover",
    model: "Sport  HSE",
    price: "89,00,000",
    registrationYear: "2018",
    registrationState: "Delhi",
    registrationNumber: "112233",
    kmDriven: "3500",
    fuelType: "Petrol",
    engineType: "1993cc, Turbocharged, In-Line 4 Cyl, DOHC",
    torque: "440 NM @ 1800 RPM",
    power: "197PS / 194BHP @ 3600 RPM",
    transmission: "9G-TRONIC Automatic Transmission",
    driveTrain: "RWD",
    thumbnail: "/images/collection/car-6.webp",
    gallery: [
      "/images/collection/car-6.webp",
      "/images/collection/car-6.webp",
      "/images/collection/car-6.webp",
    ],
    isBooked: false,
    isSoldOut: false,
    isCertified: false,
  }
];

export default cars;