const cars = [
  {
    _id: "004",
    title: "Toyota Land Cruiser LC 300",
    brand: "Toyota",
    model: "Land Cruiser LC 300",
    price: "2,49,00,000",
    registrationYear: "2022",
    registrationState: "Delhi",
    registrationNumber: "112233",
    kmDriven: "10500",
    fuelType: "Diesel",
    engineType: "1993cc, Turbocharged, In-Line 4 Cyl, DOHC",
    torque: "440 NM @ 1800 RPM",
    power: "197PS / 194BHP @ 3600 RPM",
    transmission: "9G-TRONIC Automatic Transmission",
    driveTrain: "RWD",
    thumbnail: "/images/toyota-land-cruiser-LC-300.webp",
    gallery: [
      "/images/toyota-land-cruiser-LC-300.webp",
      "/images/toyota-land-cruiser-LC-300.webp",
      "/images/toyota-land-cruiser-LC-300.webp",
    ],
    isBooked: false,
    isSoldOut: false,
    isCertified: false,
  },
  {
    _id: "005",
    title: "Mercedes-Benz AMG G 63",
    brand: "Mercedes Benz",
    model: "AMG G 63",
    price: "3,69,00,000",
    registrationYear: "2022",
    registrationState: "Delhi",
    registrationNumber: "112233",
    kmDriven: "3500",
    fuelType: "Petrol",
    engineType: "1993cc, Turbocharged, In-Line 4 Cyl, DOHC",
    torque: "440 NM @ 1800 RPM",
    power: "197PS / 194BHP @ 3600 RPM",
    transmission: "9G-TRONIC Automatic Transmission",
    driveTrain: "RWD",
    thumbnail: "/images/mercedes-benz-AMG-G-63.webp",
    gallery: [
      "/images/mercedes-benz-AMG-G-63.webp",
      "/images/mercedes-benz-AMG-G-63.webp",
      "/images/mercedes-benz-AMG-G-63.webp",
    ],
    isBooked: false,
    isSoldOut: false,
    isCertified: true,
  },
  {
    _id: "006",
    title: "Lamborghini Urus",
    brand: "Lamborghini",
    model: "Urus",
    price: "3,79,00,000",
    registrationYear: "2022",
    registrationState: "Delhi",
    registrationNumber: "112233",
    kmDriven: "3500",
    fuelType: "Petrol",
    engineType: "1993cc, Turbocharged, In-Line 4 Cyl, DOHC",
    torque: "440 NM @ 1800 RPM",
    power: "197PS / 194BHP @ 3600 RPM",
    transmission: "9G-TRONIC Automatic Transmission",
    driveTrain: "RWD",
    thumbnail: "/images/lamborghini-urus-masonry-Edition.webp",
    gallery: [
      "/images/lamborghini-urus-masonry-Edition.webp",
      "/images/lamborghini-urus-masonry-Edition.webp",
      "/images/lamborghini-urus-masonry-Edition.webp",
    ],
    isBooked: true,
    isSoldOut: false,
    isCertified: false,
  },
  {
    _id: "008",
    title: "Mercedes-Benz Gle 43 AMG",
    brand: "Mercedes Benz",
    model: "Gle 43 AMG Coupe",
    price: "6,77,00,000",
    registrationYear: "2022",
    registrationState: "Puducherry",
    registrationNumber: "112233",
    kmDriven: "33200",
    fuelType: "Petrol",
    engineType: "1993cc, Turbocharged, In-Line 4 Cyl, DOHC",
    torque: "440 NM @ 1800 RPM",
    power: "197PS / 194BHP @ 3600 RPM",
    transmission: "9G-TRONIC Automatic Transmission",
    driveTrain: "RWD",
    thumbnail: "/images/mercedes-benz-Gle-43-AMG Coupe.webp",
    gallery: [
      "/images/mercedes-benz-Gle-43-AMG Coupe.webp",
      "/images/mercedes-benz-Gle-43-AMG Coupe.webp",
      "/images/mercedes-benz-Gle-43-AMG Coupe.webp",
    ],
    isBooked: false,
    isSoldOut: false,
    isCertified: false,
  },
  {
    _id: "009",
    title: "2018 Lexus LX570",
    brand: "Lexus",
    model: "LX570",
    price: "1,89,00,000",
    registrationYear: "2022",
    registrationState: "Delhi",
    registrationNumber: "112233",
    kmDriven: "3500",
    fuelType: "Petrol",
    engineType: "1993cc, Turbocharged, In-Line 4 Cyl, DOHC",
    torque: "440 NM @ 1800 RPM",
    power: "197PS / 194BHP @ 3600 RPM",
    transmission: "9G-TRONIC Automatic Transmission",
    driveTrain: "RWD",
    thumbnail: "/images/lexus-LX570.webp",
    gallery: [
      "/images/lexus-LX570.webp",
      "/images/lexus-LX570.webp",
      "/images/lexus-LX570.webp",
    ],
    isBooked: false,
    isSoldOut: false,
    isCertified: false,
  },
  {
    _id: "0010",
    title: "Range Rover Sports Hse",
    brand: "Range Rover",
    model: "Sports Hse",
    price: "1,05,00,000",
    registrationYear: "2022",
    registrationState: "Delhi",
    registrationNumber: "112233",
    kmDriven: "3500",
    fuelType: "Petrol",
    engineType: "1993cc, Turbocharged, In-Line 4 Cyl, DOHC",
    torque: "440 NM @ 1800 RPM",
    power: "197PS / 194BHP @ 3600 RPM",
    transmission: "9G-TRONIC Automatic Transmission",
    driveTrain: "RWD",
    thumbnail: "/images/range-rover-sports-hse.webp",
    gallery: [
      "/images/range-rover-sports-hse.webp",
      "/images/range-rover-sports-hse.webp",
      "/images/range-rover-sports-hse.webp",
    ],
    isBooked: false,
    isSoldOut: false,
    isCertified: true,
  },
];
export default cars;
