const cars = [
  {
    _id: "001",
    title: "2021 Audi Rs Q8",
    brand: "Audi",
    model: "Q8",
    price: "4,99,00,000",
    registrationYear: "2021",
    registrationState: "Delhi",
    registrationNumber: "112233",
    kmDriven: "3500",
    fuelType: "Petrol",
    engineType: "1993cc, Turbocharged, In-Line 4 Cyl, DOHC",
    torque: "440 NM @ 1800 RPM",
    power: "197PS / 194BHP @ 3600 RPM",
    transmission: "9G-TRONIC Automatic Transmission",
    driveTrain: "RWD",
    thumbnail: "/images/search-results/car-1.webp",
    gallery: [
      "/images/search-results/car-1.webp",
      "/images/search-results/car-1.webp",
      "/images/search-results/car-1.webp",
    ],
    isBooked: true,
    isSoldOut: false,
    isCertified: false,
  },
  {
    _id: "002",
    title: "2022 Audi Rs Q8",
    brand: "Audi",
    model: "Q8",
    price: "3,55,00,000",
    registrationYear: "2022",
    registrationState: "Delhi",
    registrationNumber: "112233",
    kmDriven: "3500",
    fuelType: "Petrol",
    engineType: "1993cc, Turbocharged, In-Line 4 Cyl, DOHC",
    torque: "440 NM @ 1800 RPM",
    power: "197PS / 194BHP @ 3600 RPM",
    transmission: "9G-TRONIC Automatic Transmission",
    driveTrain: "RWD",
    thumbnail: "/images/search-results/car-2.webp",
    gallery: [
      "/images/search-results/car-2.webp",
      "/images/search-results/car-2.webp",
      "/images/search-results/car-2.webp",
    ],
    isBooked: false,
    isSoldOut: false,
    isCertified: true,
  },
  {
    _id: "003",
    title: "2023 Audi Rs Q8",
    brand: "Audi",
    model: "Q8",
    price: "3,55,00,000",
    registrationYear: "2023",
    registrationState: "Delhi",
    registrationNumber: "112233",
    kmDriven: "3500",
    fuelType: "Petrol",
    engineType: "1993cc, Turbocharged, In-Line 4 Cyl, DOHC",
    torque: "440 NM @ 1800 RPM",
    power: "197PS / 194BHP @ 3600 RPM",
    transmission: "9G-TRONIC Automatic Transmission",
    driveTrain: "RWD",
    thumbnail: "/images/search-results/car-3.webp",
    gallery: [
      "/images/search-results/car-3.webp",
      "/images/search-results/car-3.webp",
      "/images/search-results/car-3.webp",
    ],
    isBooked: false,
    isSoldOut: false,
    isCertified: false,
  },
  {
    _id: "004",
    title: "2021 Audi E-Tron 55 Technology",
    brand: "Audi",
    model: "E-Tron 55",
    price: "3,65,00,000",
    registrationYear: "2020",
    registrationState: "Delhi",
    registrationNumber: "112233",
    kmDriven: "3500",
    fuelType: "Petrol",
    engineType: "1993cc, Turbocharged, In-Line 4 Cyl, DOHC",
    torque: "440 NM @ 1800 RPM",
    power: "197PS / 194BHP @ 3600 RPM",
    transmission: "9G-TRONIC Automatic Transmission",
    driveTrain: "RWD",
    thumbnail: "/images/search-results/car-4.webp",
    gallery: [
      "/images/search-results/car-4.webp",
      "/images/search-results/car-4.webp",
      "/images/search-results/car-4.webp",
    ],
    isBooked: false,
    isSoldOut: false,
    isCertified: true,
  },
  {
    _id: "005",
    title: "2019 Audi A8L 55 Tfsi Quattro",
    brand: "Audi",
    model: "A8L 55",
    price: "3,69,00,000",
    registrationYear: "2023",
    registrationState: "Delhi",
    registrationNumber: "112233",
    kmDriven: "3500",
    fuelType: "Petrol",
    engineType: "1993cc, Turbocharged, In-Line 4 Cyl, DOHC",
    torque: "440 NM @ 1800 RPM",
    power: "197PS / 194BHP @ 3600 RPM",
    transmission: "9G-TRONIC Automatic Transmission",
    driveTrain: "RWD",
    thumbnail: "/images/search-results/car-5.webp",
    gallery: [
      "/images/search-results/car-5.webp",
      "/images/search-results/car-5.webp",
      "/images/search-results/car-5.webp",
    ],
    isBooked: false,
    isSoldOut: true,
    isCertified: false,
  },
  {
    _id: "006",
    title: "2019 Audi A4 40 TFSI Premium Plus",
    brand: "Audi",
    model: "A4",
    price: "89,00,000",
    registrationYear: "2020",
    registrationState: "Delhi",
    registrationNumber: "112233",
    kmDriven: "3500",
    fuelType: "Petrol",
    engineType: "1993cc, Turbocharged, In-Line 4 Cyl, DOHC",
    torque: "440 NM @ 1800 RPM",
    power: "197PS / 194BHP @ 3600 RPM",
    transmission: "9G-TRONIC Automatic Transmission",
    driveTrain: "RWD",
    thumbnail: "/images/search-results/car-6.webp",
    gallery: [
      "/images/search-results/car-6.webp",
      "/images/search-results/car-6.webp",
      "/images/search-results/car-6.webp",
    ],
    isBooked: false,
    isSoldOut: false,
    isCertified: false,
  },
  {
    _id: "007",
    title: "2019 Audi Q5 40TDI Premium Plus",
    brand: "Audi",
    model: "Q5 40TDI",
    price: "3,65,00,000",
    registrationYear: "2020",
    registrationState: "Delhi",
    registrationNumber: "112233",
    kmDriven: "3500",
    fuelType: "Petrol",
    engineType: "1993cc, Turbocharged, In-Line 4 Cyl, DOHC",
    torque: "440 NM @ 1800 RPM",
    power: "197PS / 194BHP @ 3600 RPM",
    transmission: "9G-TRONIC Automatic Transmission",
    driveTrain: "RWD",
    thumbnail: "/images/search-results/car-7.webp",
    gallery: [
      "/images/search-results/car-7.webp",
      "/images/search-results/car-7.webp",
      "/images/search-results/car-7.webp",
    ],
    isBooked: false,
    isSoldOut: false,
    isCertified: true,
  },
];

export default cars;
